---
title: Emoji animation
hero_image: images/banner.png
description:
  Create a fun animation using emojis
meta_title: Python coding projects for kids and teens | Emoji animation
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Create a fun animation using emojis. 
version: 4
listed: true
copyedit: true
last_tested: "2024-06-20"
steps:
  - title: Introduction
  - title: Your idea
  - title: Build and test - Motif
    completion:
      - engaged
  - title: Expand and test - Pattern
    completion:
      - internal
  - title: Checklist
    completion:
      - external
  - title: Upgrade your project
  - title: Share
  - title: What next?
